name: Docker Image CI

on:
  pull_request:
    branches: [ "build" ]
jobs:

  build:
  
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.TAS_FE_TOKEN}}
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: |
            docker build . --tag ghcr.io/thinhnche153157/tas_project_fe:latest
            docker push ghcr.io/thinhnche153157/tas_project_fe:latest
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
          username: root
          host: 103.179.173.136
          key: ${{secrets.SSH_PASSWORD}}
          script: |
            docker stop tas_project_fe || true  
            docker rm tas_project_fe || true  
            docker rmi ghcr.io/thinhnche153157/tas_project_fe:latest || true 
            docker run -d --name tas_project_fe --restart on-failure:5 -p 3036:80 ghcr.io/thinhnche153157/tas_project_fe:latest
